print ("\nPlease enter the following: \n")

adjetive = input("Adjetive: ")
animal = input("Animal: ")
verb1 = input("Verb: ")
exclamation = input("Exclamation: ")
verb2 = input("Verb: ")
verb3 = input("Verb: ")

print ("\nYour story is: \n")
print (f'The other day, I was really in trouble. It all started when I saw a very')
print (f'{adjetive} {animal} {verb1} down the hallway. "{exclamation.capitalize()}!" I yelled. But all')
print (f'I could think to do was to {verb2} over and over. Miraculously,')
print (f'that caused it to stop, but not before it tried to {verb3}')
print (f'right in front of my family. \n')